# Boolean Indexing

In [1]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
data = np.random.randn(7,4)

In [5]:
data

array([[ 0.00749251,  0.19613087, -0.21303039, -1.37822137],
       [ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.20493885,  0.22619734,  0.00620437,  0.20048244],
       [ 0.53111212, -0.08028868,  2.35434324, -0.5408714 ],
       [ 0.70638141,  2.58985674, -0.17953985,  2.05926446],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [6]:
names == "Bob"#check the value that it is in the arrray or not 

array([ True, False, False,  True, False, False, False])

In [7]:
data [ names == 'Bob']#print those values which are at the bob

array([[ 0.00749251,  0.19613087, -0.21303039, -1.37822137],
       [ 0.53111212, -0.08028868,  2.35434324, -0.5408714 ]])

In [8]:
data [names != 'Bob']#print those values which are not at the bob 

array([[ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.20493885,  0.22619734,  0.00620437,  0.20048244],
       [ 0.70638141,  2.58985674, -0.17953985,  2.05926446],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [9]:
data [ names == 'Bob' , 1:3]#print those values which are at the bob but with slicing

array([[ 0.19613087, -0.21303039],
       [-0.08028868,  2.35434324]])

In [10]:
data [~(names == "Bob")]#print those values which are not at the bob 

array([[ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.20493885,  0.22619734,  0.00620437,  0.20048244],
       [ 0.70638141,  2.58985674, -0.17953985,  2.05926446],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [11]:
cond = names == "Will"#Putting the values of Will in cond variable

In [12]:
cond

array([False, False,  True, False,  True, False, False])

In [13]:
data[~(cond)]#print those values which are not in the cond variable

array([[ 0.00749251,  0.19613087, -0.21303039, -1.37822137],
       [ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.53111212, -0.08028868,  2.35434324, -0.5408714 ],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [14]:
mask = (names == "Bob") |(names == "Joe")#from mask variable we can check multiple values of array
mask

array([ True,  True, False,  True, False,  True,  True])

In [15]:
data[mask]

array([[ 0.00749251,  0.19613087, -0.21303039, -1.37822137],
       [ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.53111212, -0.08028868,  2.35434324, -0.5408714 ],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [16]:
data[data == "Bob"] = 5 #those values that are equal to bob changing by 5
data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


array([[ 0.00749251,  0.19613087, -0.21303039, -1.37822137],
       [ 0.42653699,  1.22982012, -0.10550479, -0.18107713],
       [ 0.20493885,  0.22619734,  0.00620437,  0.20048244],
       [ 0.53111212, -0.08028868,  2.35434324, -0.5408714 ],
       [ 0.70638141,  2.58985674, -0.17953985,  2.05926446],
       [ 1.0837807 , -0.38149425, -1.06688176,  0.47836272],
       [ 0.84589167, -1.25916767, -0.5606503 , -0.76033621]])

In [17]:
data[data <0] = 0#those values of data that smalller then zero changing by zero
data

array([[0.00749251, 0.19613087, 0.        , 0.        ],
       [0.42653699, 1.22982012, 0.        , 0.        ],
       [0.20493885, 0.22619734, 0.00620437, 0.20048244],
       [0.53111212, 0.        , 2.35434324, 0.        ],
       [0.70638141, 2.58985674, 0.        , 2.05926446],
       [1.0837807 , 0.        , 0.        , 0.47836272],
       [0.84589167, 0.        , 0.        , 0.        ]])

# Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.


In [18]:
arr = np.empty((8,4))

In [19]:
for i in range(8):
    arr[i] = i
    

In [20]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [21]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [22]:
arr[[-3,-1,-7]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [1., 1., 1., 1.]])

In [23]:
arr[[2,3,4] , 0:3]

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [24]:
arr = np.arange(36).reshape(9,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [25]:
arr[[4,7,6,2] , [3,0,2,1]]

array([19, 28, 26,  9])

In [26]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
#1[0,3,1,2], 5[0,3,1,2], 7[0,3,1,2], 2[0,3,1,2]
#[(1,0),(1,3),(1,1),(1,2)] and so on

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [27]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [29]:
arr1 = np.random.randn(6,3)
arr1

array([[-0.96222027,  0.1336728 ,  0.73964785],
       [-0.49612272, -0.44515733, -0.24965966],
       [ 0.98672976, -0.04814232,  0.08992688],
       [ 1.49419386,  0.55117625, -0.11111232],
       [-0.02161973, -2.48851635, -0.47357688],
       [-0.65281252,  0.68823358, -1.16549993]])

In [30]:
np.dot(arr1,arr)

array([[  8.0648425 ,   7.97594288,   7.88704326,   7.79814364,
          7.70924401],
       [ -4.72238328,  -5.91332299,  -7.1042627 ,  -8.2952024 ,
         -9.48614211],
       [  0.65855716,   1.68707147,   2.71558578,   3.74410009,
          4.7726144 ],
       [  1.64475803,   3.57901582,   5.51327361,   7.4475314 ,
          9.38178919],
       [-17.17835052, -20.16206348, -23.14577644, -26.1294894 ,
        -29.11320236],
       [ -8.21383142,  -9.34391029, -10.47398916, -11.60406803,
        -12.7341469 ]])

In [31]:
data = np.arange(36).reshape(((1,6,6)))
data

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [32]:
data.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35]]])

In [33]:
data

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [34]:
data.swapaxes(2,1)

array([[[ 0,  6, 12, 18, 24, 30],
        [ 1,  7, 13, 19, 25, 31],
        [ 2,  8, 14, 20, 26, 32],
        [ 3,  9, 15, 21, 27, 33],
        [ 4, 10, 16, 22, 28, 34],
        [ 5, 11, 17, 23, 29, 35]]])

# Universal Functions: Fast Element-Wise Array Functions



In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [38]:
x = np.random.randn(7)

In [39]:
y = np.random.randn(7)

In [40]:
x


array([ 0.55938909, -0.79562989, -0.01420981,  2.26927704,  0.04662626,
       -0.00565772,  0.12561141])

In [41]:
y

array([-1.39588379, -0.36750127, -0.06774323, -0.50869096, -2.03999936,
        1.18504357, -0.3774446 ])

In [42]:
np.maximum(x,y)

array([ 0.55938909, -0.36750127, -0.01420981,  2.26927704,  0.04662626,
        1.18504357,  0.12561141])

In [43]:
arr = np.random.randn(7) * 5
arr

array([-3.86828794, -4.27181212, -2.58671265, -0.91625006, -3.52542111,
       11.05307474, -0.51294582])

In [44]:
remainder , wholepart = np.modf(arr)

In [45]:
remainder

array([-0.86828794, -0.27181212, -0.58671265, -0.91625006, -0.52542111,
        0.05307474, -0.51294582])

In [46]:
wholepart

array([-3., -4., -2., -0., -3., 11., -0.])

In [47]:
np.sqrt(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
       3.32461648,        nan])

In [48]:
np.sqrt(arr,arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
       3.32461648,        nan])

In [49]:
arr

array([       nan,        nan,        nan,        nan,        nan,
       3.32461648,        nan])

# Array-Oriented Programming with Arrays


In [50]:
names = ['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']
names

['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']

In [51]:
set(names)

{'Bob', 'Joe', 'Will'}

In [52]:
students = {"Ali","Bilal","Moshin","Ali"}
students

{'Ali', 'Bilal', 'Moshin'}

In [53]:
set(students)

{'Ali', 'Bilal', 'Moshin'}

In [54]:
arr = np.arange(24).reshape(4,-1)

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [56]:
arr = np.arange(15).reshape(3,5)

In [57]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
flat = arr.flatten()

In [62]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
ravel = arr.ravel()
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
ravel[3:9] = 0
ravel

array([ 0,  1,  2,  0,  0,  0,  0,  0,  0,  9, 10, 11, 12, 13, 14])

In [66]:
arr

array([[ 0,  1,  2,  0,  0],
       [ 0,  0,  0,  0,  9],
       [10, 11, 12, 13, 14]])

In [67]:
flat[3:9] = 0
flat

array([ 0,  1,  2,  0,  0,  0,  0,  0,  0,  9, 10, 11, 12, 13, 14])

In [68]:
arr

array([[ 0,  1,  2,  0,  0],
       [ 0,  0,  0,  0,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr1 = np.array([[7,8,9] , [10,11,12]])
arr1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [71]:
np.concatenate([arr,arr1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
np.concatenate([arr,arr1] , axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.concatenate([arr,arr1] , axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [74]:
splitt =np.arange(1,25).reshape(6,4)
splitt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [75]:
np.vsplit(splitt,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [76]:
np.hsplit(splitt,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

# Mathematical and Statistical Methods

In [78]:
arr = np.random.randn(7,4)
arr

array([[ 0.99538059, -0.84131167, -1.06795092, -0.71364528],
       [-0.2062618 , -0.96506794, -0.16961567,  1.51720443],
       [ 0.65175188,  0.12079575, -0.50411371, -0.82300184],
       [-0.39234196, -0.75054447,  0.18937047, -0.32951494],
       [ 0.52699397, -0.54917505, -0.47703442,  1.00690503],
       [ 1.17278612, -0.11026919, -1.453888  ,  3.26589947],
       [-0.64625578, -1.74782662, -0.31006549,  1.21373525]])

In [79]:
arr.mean()

-0.04989506337027238

In [80]:
arr.sum()

-1.3970617743676266

In [2]:
data = np.array([1,2,3,4,5,6,7,8,9])
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
data.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

# Sorting


In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.array([6,7,8,3,1,4,0,5,1,9])
arr

array([6, 7, 8, 3, 1, 4, 0, 5, 1, 9])

In [7]:
arr.sort()

In [8]:
arr

array([0, 1, 1, 3, 4, 5, 6, 7, 8, 9])

In [9]:
ar = np.random.randn(5,3)
ar


array([[ 1.99457484, -0.21899703, -0.52379354],
       [ 1.43722272, -3.01042536, -1.30981631],
       [-0.19129167,  0.88466816, -2.26150288],
       [-0.52051845, -0.05071539,  1.70949898],
       [ 1.82191689,  0.04058921,  1.81088343]])

In [10]:
ar.sort()
ar

array([[-0.52379354, -0.21899703,  1.99457484],
       [-3.01042536, -1.30981631,  1.43722272],
       [-2.26150288, -0.19129167,  0.88466816],
       [-0.52051845, -0.05071539,  1.70949898],
       [ 0.04058921,  1.81088343,  1.82191689]])